package ejerciciosueldoventana;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class pantalla extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();
    public pantalla() {
        initComponents();
        
        
        TXT_cesantias.setEnabled(false);
        TXT_Interes_cesan.setEnabled(false);
        TXT_Vacaciones.setEnabled(false);
        TXT_Prima.setEnabled(false);
        TXT_Liquidacion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXT_salario = new javax.swing.JTextField();
        TXT_Dias = new javax.swing.JTextField();
        TXT_cesantias = new javax.swing.JTextField();
        TXT_Interes_cesan = new javax.swing.JTextField();
        TXT_Vacaciones = new javax.swing.JTextField();
        TXT_Prima = new javax.swing.JTextField();
        TXT_Liquidacion = new javax.swing.JTextField();
        Boton_calcular = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salario");

        jLabel2.setText("Dias trabajados");

        jLabel3.setText("Cesantias");

        jLabel4.setText("Interes cesantias");

        jLabel5.setText("Vacaciones");

        jLabel6.setText("Prima");

        jLabel7.setText("Liquidacion");

        TXT_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_salarioActionPerformed(evt);
            }
        });
        TXT_salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_salarioKeyTyped(evt);
            }
        });

        TXT_Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_DiasActionPerformed(evt);
            }
        });
        TXT_Dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_DiasKeyTyped(evt);
            }
        });

        TXT_cesantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_cesantiasActionPerformed(evt);
            }
        });

        TXT_Interes_cesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_Interes_cesanActionPerformed(evt);
            }
        });

        TXT_Vacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_VacacionesActionPerformed(evt);
            }
        });

        TXT_Prima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PrimaActionPerformed(evt);
            }
        });

        TXT_Liquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LiquidacionActionPerformed(evt);
            }
        });

        Boton_calcular.setText("Calcular");
        Boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_calcularActionPerformed(evt);
            }
        });

        Boton_Salir.setText("Salir");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });

        TextoArea.setColumns(20);
        TextoArea.setRows(5);
        jScrollPane1.setViewportView(TextoArea);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_Liquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_Prima, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_Vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_Interes_cesan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_cesantias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXT_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(128, 128, 128)
                                .addComponent(TXT_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(177, 177, 177)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_calcular)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Boton_Salir)))
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXT_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXT_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXT_cesantias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXT_Interes_cesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_Vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXT_Prima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_Liquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Boton_calcular)
                        .addGap(26, 26, 26)
                        .addComponent(Boton_Salir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_salarioActionPerformed

    private void TXT_DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_DiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_DiasActionPerformed

    private void TXT_cesantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_cesantiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_cesantiasActionPerformed

    private void TXT_Interes_cesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_Interes_cesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_Interes_cesanActionPerformed

    private void TXT_VacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_VacacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_VacacionesActionPerformed

    private void TXT_PrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PrimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_PrimaActionPerformed

    private void TXT_LiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LiquidacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_LiquidacionActionPerformed

    private void Boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_calcularActionPerformed
        if (TXT_salario.getText().equals("") || TXT_Dias.getText().equals("")) {
            //error
            JOptionPane.showMessageDialog(rootPane, "Error. Los textos no pueden estar vacios", " errores", HEIGHT);

        } else {
            double salario, dias, cesantias, interesce, vacaciones, prima, total;
            salario = Double.parseDouble(TXT_salario.getText());
            dias = Double.parseDouble(TXT_Dias.getText());
            
            if (salario >= 1000000) {
                if (dias>=1) {
                    if (dias <= 360) {
                        String resul;

                        cesantias = (salario * dias) / 360;

                        interesce = (cesantias * 12) / 100;
                        vacaciones = (salario * dias) / 720;
                        prima = (salario * dias) / 720;

                        total = cesantias + interesce + vacaciones + prima;

                        TXT_cesantias.setText(String.valueOf(cesantias));
                        TXT_Interes_cesan.setText(String.valueOf(interesce));
                        TXT_Vacaciones.setText(String.valueOf(vacaciones));
                        TXT_Prima.setText(String.valueOf(prima));
                        TXT_Liquidacion.setText(String.valueOf(total));

                        TXT_Liquidacion.setText(String.valueOf(total));
                        resul = "Salario: " + salario + "\n Dias Trabajados: " + dias + "\n Cesantias: " + cesantias + "\n Interes: " + interesce + "\n Vacaciones: " + vacaciones
                                + "\n Prima: " + prima + "\n TOTAL: " + total;
                        TextoArea.setText(resul);
                        
                        model.addElement(resul);
                        jList1.setModel(model);
                    } else {
                        System.out.println("Los dias no puede ser mayor a 360.");
                        TXT_cesantias.setText("");
                        TXT_Interes_cesan.setText("");
                        TXT_Vacaciones.setText("");
                        TXT_Prima.setText("");
                        TXT_Liquidacion.setText("");
                        TextoArea.setText("");
                    }
                } else {
                    System.out.println("Los dias no puede ser menor a 1.");
                    TXT_cesantias.setText("");
                    TXT_Interes_cesan.setText("");
                    TXT_Vacaciones.setText("");
                    TXT_Prima.setText("");
                    TXT_Liquidacion.setText("");
                    TextoArea.setText("");
                }
                
            } else {
                System.out.println("El salario no puede ser menor al salario minimo.");
                TXT_cesantias.setText("");
                TXT_Interes_cesan.setText("");
                TXT_Vacaciones.setText("");
                TXT_Prima.setText("");
                TXT_Liquidacion.setText("");
                TextoArea.setText("");
            }

        }
    }//GEN-LAST:event_Boton_calcularActionPerformed

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "Realmente desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void TXT_salarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_salarioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_salarioKeyTyped

    private void TXT_DiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_DiasKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (TXT_Dias.getText().trim().length() == 10) {
            evt.consume();
        }
        if (TXT_Dias.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_DiasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_calcular;
    private javax.swing.JTextField TXT_Dias;
    private javax.swing.JTextField TXT_Interes_cesan;
    private javax.swing.JTextField TXT_Liquidacion;
    private javax.swing.JTextField TXT_Prima;
    private javax.swing.JTextField TXT_Vacaciones;
    private javax.swing.JTextField TXT_cesantias;
    private javax.swing.JTextField TXT_salario;
    private javax.swing.JTextArea TextoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
